// Authenticaiton.
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER = 'LOGIN_USER'

export const LOGOUT_USER_REQUEST = 'LOGOUT_USER_REQUEST'
export const LOGOUT_USER = 'LOGOUT_USER'

export const CHANGE_PASSWORD_REQUEST = 'CHANGE_PASSWORD_REQUEST'

// Notification message.
export const SHOW_MESSAGE_REQUEST = 'SHOW_MESSAGE_REQUEST'
export const SHOW_MESSAGE = 'SHOW_MESSAGE'
export const HIDE_MESSAGE = 'HIDE_MESSAGE'

// Users.
export const LOAD_USERS_REQUEST = 'LOAD_USERS_REQUEST'
export const LOAD_USERS = 'LOAD_USERS'

export const ADD_USER_REQUEST = 'ADD_USER_REQUEST'
export const ADD_USER = 'ADD_USER'

export const GET_USER_REQUEST = 'GET_USER_REQUEST'
export const GET_USER = 'GET_USER'

export const UPDATE_USER_REQUEST = 'UPDATE_USER_REQUEST'
export const UPDATE_USER = 'UPDATE_USER'

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST'
export const DELETE_USER = 'DELETE_USER'

// Sheets.
export const LOAD_SHEETS_REQUEST = 'LOAD_SHEETS_REQUEST'
export const LOAD_SHEETS = 'LOAD_SHEETS'

export const ADD_SHEET_REQUEST = 'ADD_SHEET_REQUEST'
export const ADD_SHEET = 'ADD_SHEET'

export const GET_SHEET_REQUEST = 'GET_SHEET_REQUEST'
export const GET_SHEET = 'GET_SHEET'

export const UPDATE_SHEET_REQUEST = 'UPDATE_SHEET_REQUEST'
export const UPDATE_SHEET = 'UPDATE_SHEET'

export const DELETE_SHEET_REQUEST = 'DELETE_SHEET_REQUEST'
export const DELETE_SHEET = 'DELETE_SHEET'

// Leads.
export const IMPORT_LEADS_REQUEST = 'IMPORT_LEADS_REQUEST'
export const IMPORT_LEADS = 'IMPORT_LEADS'

export const LOAD_LEADS_REQUEST = 'LOAD_LEADS_REQUEST'
export const LOAD_LEADS = 'LOAD_LEADS'

export const ADD_LEAD_REQUEST = 'ADD_LEAD_REQUEST'
export const ADD_LEAD = 'ADD_LEAD'

export const GET_LEAD_REQUEST = 'GET_LEAD_REQUEST'
export const GET_LEAD = 'GET_LEAD'

export const UPDATE_LEAD_REQUEST = 'UPDATE_LEAD_REQUEST'
export const UPDATE_LEAD = 'UPDATE_LEAD'

export const DELETE_LEAD_REQUEST = 'DELETE_LEAD_REQUEST'
export const DELETE_LEAD = 'DELETE_LEAD'

export const READ_TWEETS_REQUEST = 'READ_TWEETS_REQUEST'
