export default {
  DB_URI: 'YOUR_MONGODB_URI',
  SESSION_SECRET: 'YOUR_SESSION_SECRET',
  TWITTER_CONSUMER_KEY: 'YOUR_TWITTER_CONSUMER_KEY',
  TWITTER_CONSUMER_SECRET: 'YOUR_TWITTER_CONSUMER_SECRET',
  DEFAULT_USER: {
    username: 'DEFAULT_USER_NAME',
    password: 'DEFAULT_USER_PASSWORD',
  },
}
